### ISSUE TITLE
Windows 7 BSOD cutting off at the top-left

### ISSUE THREAD

**Issue by ayjemabo** [FlyTechVideos/BluescreenSimulator#101]
![Screenshot (12)](https://user-images.githubusercontent.com/95683302/145017730-90bc2714-dcef-43b5-b9e1-321477a4b879.png)
I don't want it to cut off

**Comment by ayjemabo** [comment]
can anyone fix it?

> **staticRoco** added the bug label 10 hours ago

**Comment by staticRoco** [comment]
What's your screen resolution?

**Comment by ayjemabo** [comment]
> 

1920x1080

**Comment by ayjemabo** [comment]
> What's your screen resolution?

The resolution is 1920 by 1080 pixels

**Comment by staticRoco** [comment]
Can't repro on a 1920x1080 screen.

![image](https://user-images.githubusercontent.com/43659330/145439734-ae65bfa9-d685-46ce-81cb-47da19687586.png)

**Comment by ayjemabo** [comment]
> Can't repro on a 1920x1080 screen.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/43659330/145439734-ae65bfa9-d685-46ce-81cb-47da19687586.png)
> 
> 

What do you mean?

**Comment by ayjemabo** [comment]
```
Are you on a 4K?
```

**Comment by ayjemabo** [comment]
> Can't repro on a 1920x1080 screen.
> 
> ![image](https://user-images.githubusercontent.com/43659330/145439734-ae65bfa9-d685-46ce-81cb-47da19687586.png)

Have you got a 4K screen? Because my max is 1920x1080 AND on youtube 8K

**Comment by staticRoco** [comment]
Not sure how that's relevant to your issue? 

Unable to repro on a monitor with the same resolution.
Could be hardware related issue, tagging this as invalid and closing it.

**Comment by ayjemabo** [comment]
> Not sure how that's relevant to your issue? 
> 
> 
> 
> Unable to repro on a monitor with the same resolution.
> 
> Could be hardware related issue, tagging this as invalid and closing it.

My software was not updated but now it's updated and it's perfectly fine
