### ISSUE TITLE
NORTON PROBLEM

### ISSUE THREAD

**Issue by Velcro3** [FlyTechVideos/BluescreenSimulator#104]
Norton detects this as _____.MBT.Trojan

**Comment by bazthedev** [comment]
I experienced the same issue

**Comment by Flytechfan101** [comment]
I experienced it with both Windows Defender and Avast.

**Comment by 0xRoco** [comment]
this is a false positive.
Use the search field before making an issue.
[VirusTotal scan](https://www.virustotal.com/gui/file/a872ab63fd3e70627d7bf28a74045a5fca407d79a950ac1fdbcecd6b7672469f/)
