### ISSUE TITLE
On Run Self-Extracting File Nothing Changes #Bug

### ISSUE THREAD

**Issue by jsienkiewicz13** [FlyTechVideos/BluescreenSimulator#108]
Help, I Run My BSOD Self-Extracting File, And It Showed Nothing, Literally Nothing Changes

**Comment by jsienkiewicz13** [comment]
Please Help

**Comment by FlyTechVideos** [comment]
Please share the exact configuration, otherwise I am unable to help. Either way, check out the latest version, maybe it fixes your problems: https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0
