### ISSUE TITLE
My antivirus (Avast) is calling it Malicious Software (Malware for novices). What should I do?

### ISSUE THREAD

**Issue by Flytechfan101** [FlyTechVideos/BluescreenSimulator#109]
Hello!

My antivirus is moving this software to quarantine whenever I try to download it because it thinks it is malware. I watch FlyTech and trust this peice of software.

Can you fix this issue?

-Flytechfan101

PS: If there is nothing you can do, I will install it by releasing it from quarantine.

**Comment by Flytechfan101** [comment]
If there is nothing you can do I will just install it anyways.

**Comment by star08-web** [comment]
is unsigned, so the AV sign tha at Malware here we go again

**Comment by star08-web** [comment]
it is not signed so the antivirus marks it as malicious, here we go again Avast

**Comment by 0xRoco** [comment]
this is a false positive.
Use the search field before making an issue.
[VirusTotal scan](https://www.virustotal.com/gui/file/a872ab63fd3e70627d7bf28a74045a5fca407d79a950ac1fdbcecd6b7672469f/)
