### ISSUE TITLE
Windows Defender is bugging me when I download it.

### ISSUE THREAD

**Issue by n0b0py** [FlyTechVideos/BluescreenSimulator#110]
For some reason, right when I download it, Windows Defender seems to always bug me.
Video of it happening: WHY 10MB MAX FILE SIZE!?!?!?!!?
Fine, a screenshot
![nooo](https://user-images.githubusercontent.com/92056558/158897192-8a5adeaa-f04a-4d95-b9ee-8fa84bff2a1a.png)
:

**Comment by CyberVictoryMan** [comment]
its not signed that is why it detects as a virus, even this issue is related to avast #109

**Comment by 0xRoco** [comment]
this is a false positive.
Use the search field before making an issue.
[VirusTotal scan](https://www.virustotal.com/gui/file/a872ab63fd3e70627d7bf28a74045a5fca407d79a950ac1fdbcecd6b7672469f/)
