### ISSUE TITLE
The Bsod .exe Is a Virus That Windows Defender Found

### ISSUE THREAD

**Issue by AnyBlecks** [FlyTechVideos/BluescreenSimulator#111]
windows defender track the virus, i cant show to thing again because i got virus so here is my protection history.
![proof](https://user-images.githubusercontent.com/102269795/159825325-e3568c0f-c98a-4749-96c2-70b70d7395a8.png)

**Comment by AnyBlecks** [comment]
i have the virus again, here is the proof
![Screenshot 2022-03-25 074204](https://user-images.githubusercontent.com/102269795/160142905-361e55e1-b2f4-4f48-8d35-d8ff6fd29f0c.png)

**Comment by ElliotTheCool** [comment]
I'm having the same problem. Here's a video of me having the same problem... https://www.transfernow.net/dl/20220411GhJyBQSP (The link is valid for 7 days, so be quick)

**Comment by 0xRoco** [comment]
this is a false positive.
Use the search field before making an issue.
[VirusTotal scan](https://www.virustotal.com/gui/file/a872ab63fd3e70627d7bf28a74045a5fca407d79a950ac1fdbcecd6b7672469f/)
