### ISSUE TITLE
it says i dont have the proper permisions

### ISSUE THREAD

**Issue by EnderBoi201** [FlyTechVideos/BluescreenSimulator#112]

**Comment by ElliotTheCool** [comment]
I have the same problem.

**Comment by Flytechfan101** [comment]
This happened to me, too!

**Comment by 0xRoco** [comment]
Run it as Administrator.

**Comment by SamyoFox** [comment]
If running it as administrator didnt work, your antivirus may be blocking the program from running. see #137

**Comment by FlyTechVideos** [comment]
This happens when the AV steals away the application. The only way to fix this is to go to Defender and whitelist the application. Check out the readme for a few links to help you with that.
