### ISSUE TITLE
Windows Defender preventing the application from starting

### ISSUE THREAD

**Issue by Pixel556** [FlyTechVideos/BluescreenSimulator#115]
Windows defender is not letting me open the application. I get this popup. Even when Real-time protection is enabled, the popup still appears.
![image](https://user-images.githubusercontent.com/95143545/166139392-ddd185ad-4d1d-44fd-bd24-8df0e13589f7.png)

**Comment by aeo2625253** [comment]
you might need to allow it on your device.

**Comment by Pixel556** [comment]
How?

**Comment by Pixel556** [comment]
Got it to work. First disable antivirus and THEN open it, click more info and run, and done
