### ISSUE TITLE
The Windows 7 BSOD uses the wrong font.

### ISSUE THREAD

**Issue by yum13241** [FlyTechVideos/BluescreenSimulator#117]
It's supposed to use the Lucida Console font, according to Wikipedia https://en.wikipedia.org/wiki/Blue_screen_of_death

The W7 BSOD looks wrong.

**Comment by FlyTechVideos** [comment]
The W7 BSOD uses Lucida Console. I think it looks wrong simply because it is using full resolution, which the real W7 BSOD does not do. I do not think this can be fixed from our side except by crashing the graphics driver, which would truly turn this thing into malware :D

**Comment by yum13241** [comment]
Can't you just change the desktop resolution? I know it's a a hacky solution so keep that as a checkbox.
