### ISSUE TITLE
Windows 9x is too slow

### ISSUE THREAD

**Issue by Orange-Fire-Computer** [FlyTechVideos/BluescreenSimulator#118]
Normally, Windows 9x underscore at the end is normally like 2sec (idk) and it takes like 7sec! I don't think it's my wi-fi I think it's the app (idk) Pls help (If could be my wi-fi I'm not sure). 😃

**Comment by Orange-Fire-Computer** [comment]
It might be better now I'm not sure

**Comment by Orange-Fire-Computer** [comment]
But please help anyway :(

**Comment by walker84837** [comment]
I don't think it's about your Wi-Fi. From what you said, you're saying the underscore in the blue screen of death is blinking slower. I think it's more about your computer and not about your Wi-Fi. I downloaded the latest version and didn't see anything like it.

**Comment by BRPScholar** [comment]
Yeah I got that too, and I try to press a key, but since my keys don't work, I have to restart.

**Comment by Orange-Fire-Computer** [comment]
ah ok thx

**Comment by FlyTechVideos** [comment]
Works properly for me ... the latest release should fix some of your problems:
https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0

If anything is still broken, feel free to reopen or create a new issue. Thank you!
