### ISSUE TITLE
Exiting BSOD

### ISSUE THREAD

**Issue by HappyYomar** [FlyTechVideos/BluescreenSimulator#119]
My F7 Turns off my Laptop pad, is there any other way to exit the BSOD without pressing F7?

**Comment by EBugYT** [comment]
Try fn+f7

**Comment by FlyTechVideos** [comment]
The BSOD should now focus automatically. The issue should be fixed now; please try again:
https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0

(Try both F7 and Fn+F7)
