### ISSUE TITLE
dark mode after cat walked over keyboard

### ISSUE THREAD

**Issue by CyberKite** [FlyTechVideos/BluescreenSimulator#120]
well, i had a cat running over my keyboard(compact layout) and Bluescreen sim had gone dark scheme(except of the top) deleting and re-downloading didn't help, so it is probably a registry thing
![Screenshot 2022-07-26 101220](https://user-images.githubusercontent.com/105157571/180957266-efedffde-a88f-4d33-94ab-bc9a50c2e8d3.png)

**Comment by SamyoFox** [comment]
You can switch between dark and light mode by pressing F12
