### ISSUE TITLE
Command after complete

### ISSUE THREAD

**Issue by Clippy-0** [FlyTechVideos/BluescreenSimulator#121]
The command after complete doesn't work. When I enable unsafe mode (`BluescreenSimulator.exe --enable-unsafe`), it displays program help.
![image](https://user-images.githubusercontent.com/91493834/182850471-82fdc634-3076-42f5-9f5e-7229b899af55.png)

**Comment by Colorowyy** [comment]
Bro i found out the problem, get into PowerShell type cd desktop and thentry typing `.\BluescreenSimulator.exe ––enable-unsafe ––win10` this should work

**Comment by Maxey1950** [comment]
It is .\BluescreenSimulator.exe --win10  --enable-unsafe

**Comment by FlyTechVideos** [comment]
3.4.0 will have unsafe mode enabled by default. Will be released soon.

**Comment by FlyTechVideos** [comment]
No more unsafe mode! Commands now just work without you specifying unsafe mode. Try it: https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0
