### ISSUE TITLE
antivirus issue

### ISSUE THREAD

**Issue by treatmeniceplz** [FlyTechVideos/BluescreenSimulator#122]
this program wont download due to virus detected and i cant even keep it

may i add i am using microsoft edge

**Comment by walker84837** [comment]
It's a false positive, which means your antivirus reports this program is malware, but it is **not** anything dangerous. Add an exception for the file in your antivirus and you'll be able to download it.

**Comment by treatmeniceplz** [comment]
How am I supposed to do that when I can't download the file

**Comment by SamyoFox** [comment]
See #137
