### ISSUE TITLE
Custom error text goes away after exe file made

### ISSUE THREAD

**Issue by Herobrine8761** [FlyTechVideos/BluescreenSimulator#123]
I created a BSOD with rainbow colors, and when I created the EXE file and ran it, the colors were fine as well as the text color was also ok but the custom error text with the custom error code went away. Please fix this bug in the next update. Thank you.

**Comment by SmirbYrneh420** [comment]
For me some of the text was changed but not all of it

**Comment by FlyTechVideos** [comment]
Should be fixed with 3.4.0 -> Get it here: https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0
