### ISSUE TITLE
How to download

### ISSUE THREAD

**Issue by Orange-Fire-Computer** [FlyTechVideos/BluescreenSimulator#124]
I can't find a download button it used to be a .exe file but now I can't find a way how to run or download please help

**Comment by Orange-Fire-Computer** [comment]
Don't worry I found it now :)

**Comment by jhfhngj** [comment]
I have the same issue but before, I got it

**Comment by Orange-Fire-Computer** [comment]
:)

**Comment by jhfhngj** [comment]
...

**Comment by jhfhngj** [comment]
Tell me the solution, please...

**Comment by jhfhngj** [comment]
I GOT IT, THANK THE BROWSER/GITHUB/THE OWNER OF THE APP
