### ISSUE TITLE
Unsafe mode problem 

### ISSUE THREAD

**Issue by Colorowyy** [FlyTechVideos/BluescreenSimulator#126]
Maybe I’m dumb maybe not but I can’t enter unsafe mode in CMD nor PowerShell. As shown in tutorial I typed `BluescreenSimulator.exe ––enable-unsafe` and it does nothing.

**Comment by Maxey1950** [comment]
It is now .\BluescreenSimulator.exe --win10  --enable-unsafe

**Comment by Colorowyy** [comment]
It’s not working

**Comment by FlyTechVideos** [comment]
No more unsafe mode! Commands now just work without you specifying unsafe mode. Try it: https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0
