### ISSUE TITLE
Generated EXE has some changes from intended effect

### ISSUE THREAD

**Issue by SmirbYrneh420** [FlyTechVideos/BluescreenSimulator#127]
![65D5364A-200D-40E6-8C72-050D4D1C8D37](https://user-images.githubusercontent.com/110212580/200152301-d0fee8a4-8cb1-4193-b1eb-dd5ad0553199.jpeg)
This is the intended BSOD.

![43600DE8-475A-4EAA-B250-5F87D4A6DE24](https://user-images.githubusercontent.com/110212580/200152312-f7e9dd45-9b11-4056-96a8-742ae2c48f7a.jpeg)
This is the BSOD from the generated EXE.

NOTE: I HAVE SCRIBBLED OVER SOME PERSONAL INFORMATION. DO NOT ATTEMPT TO EXPOSE THEM.

**Comment by FlyTechVideos** [comment]
Should be fixed with 3.4.0 -> Get it here: https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0
