### ISSUE TITLE
Original Blue QR Code doesn't work

### ISSUE THREAD

**Issue by PacfcpOFC** [FlyTechVideos/BluescreenSimulator#128]
Original Blue QR Code doesn't work

**Comment by SamyoFox** [comment]
That is a leftover from an older build, where you could still generate your own QR codes.

**Comment by FlyTechVideos** [comment]
Should be fixed with 3.4.0 -> Get it here: https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0
