### ISSUE TITLE
BSOD exit automatically upon reaching 100%

### ISSUE THREAD

**Issue by Fortress937** [FlyTechVideos/BluescreenSimulator#130]
The blue screen exit automatically after reaching 100% , i want bsod to display it permanently instead of being timed out and exit after reaching 100% in the certain time.

Feature to add:

1. Toggle option whenever the percentage advances automatically or not.
2. Exit BSOD manually instead of automatically exit upon reaching 100%

#enhancement

**Comment by Male234** [comment]
#good idea

**Comment by BRPScholar** [comment]
I wish I could do that, but my keys don't work. I have to restart the computer every time.

**Comment by FlyTechVideos** [comment]
Not a toggle, but in version 3.4.0 you can now specify a delay before the BSOD closes automatically. If you wish, you can make that delay 10 minutes or even higher. Should be sufficient for this usecase.

Get it here: https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0
