### ISSUE TITLE
antivirus

### ISSUE THREAD

**Issue by wowthisisarandomuser** [FlyTechVideos/BluescreenSimulator#131]
my antivirus said it was infrected with win32:malware

**Comment by Male234** [comment]
This is not a virus. Also just to know, what is the antivirus that you are using?

**Comment by wowthisisarandomuser** [comment]
im using avast one just so you know

**Comment by 2010phoenix** [comment]
This isn't really an issue, but my Antivirus says that this could steal my personal data, well, that doesn't seem like much. Forgot I was in Unsafe mode heh

**Comment by SamyoFox** [comment]
See #137
