### ISSUE TITLE
About anti-virus detections

### ISSUE THREAD

**Issue by SamyoFox** [FlyTechVideos/BluescreenSimulator#137]
Sometimes, BluescreenSimulator will be flagged as malware by several anti-virus programs (Avast, AVG, Norton, McAfee, Windows Defender, etc.), this however is a false positive. 
2 things cause this to happen:
    a) Because the program executable isn't signed
    b) Some antiviruses detect this as a joke program (which it is)

The program is safe. If you feel more comfortable compiling it yourself, go ahead.

For a tutorial on how to exclude this program from your antivirus so it can run anyway, check out these links:

- Windows Defender: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26
- Avast: https://support.avast.com/en-ww/article/Antivirus-scan-exclusions#pc
- AVG: https://support.avg.com/SupportArticleView?l=en&urlName=avg-antivirus-scan-exclusion
- Norton: https://support.norton.com/sp/en/us/home/current/solutions/v3672136
- McAfee: https://www.mcafee.com/support/?page=shell&shell=article-view&articleId=TS102056
- For other antiviruses, try searching for "<your antivirus name> add exception"

**Comment by FlyTechVideos** [comment]
I added this info to the readme.
