### ISSUE TITLE
Win Security (Joke:Win32/ScreenMate)

### ISSUE THREAD

**Issue by BoogieHasFun** [FlyTechVideos/BluescreenSimulator#140]
This program causes Windows Security to freak out and detect this as a threat. 

It tells me: Joke:Win32/ScreenMate
Most likely, this is a false positive due to the meaning of Joke:Win32/ScreenMate, which is a program (or malware) that is made to be annoying. 

Microsoft describes it as "This threat can change the way your PC behaves - usually in a way that is designed to be annoying."

So my question is: Is this really intentional (not as a malware) or just a false positive?

**Comment by SamyoFox** [comment]
Please see #137

**Comment by BoogieHasFun** [comment]
okay :D
