### ISSUE TITLE
F7 and Alt+F4 doesn't work, Windows 9x not closing

### ISSUE THREAD

**Issue by BRPScholar** [FlyTechVideos/BluescreenSimulator#146]
When I operate a BSOD and try to exit, the keys don't work and I have to wait for the progress to reach 100%. One time I tried a Windows 9x. When I pressed any key to continue, it didn't work. I had to restart the computer.

**Comment by FlyTechVideos** [comment]
Try clicking inside the BSOD, that should fix it. A fix that automatically requests focus is coming soon.

**Comment by FlyTechVideos** [comment]
Will be fixed with #149 in version 3.4.0.
