### ISSUE TITLE
Investigate XP compatibility

### ISSUE THREAD

**Issue by FlyTechVideos** [FlyTechVideos/BluescreenSimulator#15]

**Comment by iiRoco** [comment]
XP Supports ends in .Net Framework 3.5 i think?

**Comment by jeuxjeux20** [comment]
.NET Framework 4 Client profile actually

**Comment by jeuxjeux20** [comment]
Wait windows xp also supports the full .NET framework 4.

**Comment by dR1pT** [comment]
just build the simulator using the older .NET

**Comment by jeuxjeux20** [comment]
Tried to do it, but it's missing many features:

- Tasks and await
- Delegates
- GetCustomAttribute

**Comment by dR1pT** [comment]
I will close this issue because it's inactive and, as jeux said, older .NET lacks some important features
