### ISSUE TITLE
Detected as Malware (Obviously False Positive)

### ISSUE THREAD

**Issue by FurtherSecrets24680** [FlyTechVideos/BluescreenSimulator#151]
After downloading, I can't even whitelist this app on windows defender. Detects as - Wacatac.b!ml

**Comment by FlyTechVideos** [comment]
@FurtherSecrets24680 You should be able to whitelist it ... what prevents you? Please note that you need admin rights to whitelist an executable. There is sadly nothing I can do about this, but at least my defender does not flag the original EXE (only the generated autolaunching files)

**Comment by FurtherSecrets24680** [comment]
When I download it, it immediately detects as malware and automatically deletes it before i can even reach windows defender.

**Comment by PeasIn** [comment]
@FurtherSecrets24680 you can turn off real-time protection in windows security, whitelist the app, then turn it back on

**Comment by BH-Playz** [comment]
@FlyTechVideos? Maybe just remove Trojan:Win32\Wacatac.b!ml from BlueScreenSimulator?

**Comment by BH-Playz** [comment]
@FlyTechVideos?? Hello?

**Comment by SamyoFox** [comment]
You can't remove it, since it's not there. It's a false-positive.
