### ISSUE TITLE
Previous release didn't have malware, why does the latest?

### ISSUE THREAD

**Issue by NagaSpntis** [FlyTechVideos/BluescreenSimulator#155]
![image](https://github.com/FlyTechVideos/BluescreenSimulator/assets/44819642/bd3e31b7-3024-4370-b23a-8d543efcfd7f)

**Comment by Redactedslair** [comment]
its a false positive. since the project is open source, you can check the code itself and see what its doing. these are false positives and the program doesnt cause any harm to the computer.

**Comment by SamyoFox** [comment]
> its a false positive. since the project is open source, you can check the code itself and see what its doing. these are false positives and the program doesnt cause any harm to the computer.

Thats true, if you feel safer, compile it yourself. AVs mostly flag this because its a Joke program, but also because of the included EXE generation feature.
