### ISSUE TITLE
Chrome blocking/canceling file download

### ISSUE THREAD

**Issue by NateTheMusketeer** [FlyTechVideos/BluescreenSimulator#160]
I was trying to download this as a joke but chrome blocked the download
<img width="226" alt="snipsnap" src="https://github.com/FlyTechVideos/BluescreenSimulator/assets/146526486/3cf9923f-f200-4c0d-86e1-4166487d2f7f">
I don't know if it's blocked by any other browsers, but even disabling my antivirus won't help.

**Comment by realthrottle** [comment]
I had the same issue, but with Microsoft Edge

**Comment by SamyoFox** [comment]
That is a false-positive, please see the README.
