### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by realthrottle** [FlyTechVideos/BluescreenSimulator#161]
Microsoft SmartScreen is blocking it from being downloaded, even though I allow it, its will still block it

**Comment by Ollie4938** [comment]
winsecurity too. whats going on?

**Comment by SamyoFox** [comment]
That is a false-positive, please see the README.

**Comment by realthrottle** [comment]
so like i download it and then it says "can't download - virus detected" and it will just force me to block it even though i allow it
