### ISSUE TITLE
chrome doesnt let me download it

### ISSUE THREAD

**Issue by gnusinrat** [FlyTechVideos/BluescreenSimulator#162]
please help, chrome doesnt let me download the latest version
this is not really the program itself, but me being stupid and not knowing how to download it anyways.
it says that its a virus there, and the same with all the other versions except 2.0
(i know its not a virus)

(video below)
the video is russian because i am, but windows defender really does freak out on the file

https://github.com/FlyTechVideos/BluescreenSimulator/assets/132365312/1fa1ed03-32b0-4e40-98a7-cb026395aab0

**Comment by realthrottle** [comment]
it happened with me

**Comment by Aisultan14366** [comment]
same my windows defender removed it cuz it has TrojanDropper:Win64/Blusimul.ARA!MTB inside #164 #

https://github.com/FlyTechVideos/BluescreenSimulator/assets/148531623/e5f4ce1c-18ea-4c45-bcb9-3ac2942c4

**Comment by demo308** [comment]
it is not virus it is false postive click 3 dots downloads and resume

**Comment by joemamba55** [comment]
Bro im pretty sure demo308 is a bot and is tryna get ppl to get the virus

**Comment by SamyoFox** [comment]
The detection is a false-positive. Please read the "About anti-virus detection" section in the README.md.
