### ISSUE TITLE
Windows 11 "not made for this Windows version"

### ISSUE THREAD

**Issue by lordgatto6615** [FlyTechVideos/BluescreenSimulator#163]
i have windows 11 but my computer says the file can't be opened because is on a wrong version for my computer

**Comment by SamyoFox** [comment]
Try redownloading the file, more often than not this happens because the file hasn't been downloaded fully.

**Comment by realthrottle** [comment]
I can't even download it.

**Comment by SamyoFox** [comment]
> I can't even download it.

Please read the "About anti-virus detection" section in the README.md
