### ISSUE TITLE
Chrome thinks it's a virus. It isn't.

### ISSUE THREAD

**Issue by Feni0123456789** [FlyTechVideos/BluescreenSimulator#164]
What do I do???

**Comment by demo308** [comment]
it is not virus it is false postive click 3 dots downloads and resume

**Comment by demo308** [comment]
Windows Defender: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26
Avast: https://support.avast.com/en-ww/article/Antivirus-scan-exclusions#pc
AVG: https://support.avg.com/SupportArticleView?l=en&urlName=avg-antivirus-scan-exclusion
Norton: https://support.norton.com/sp/en/us/home/current/solutions/v3672136
McAfee: https://www.mcafee.com/support/?page=shell&shell=article-view&articleId=TS102056
For other antiviruses, try searching for "<antivirus name> add exception"

**Comment by SamyoFox** [comment]
Yes, it is a false-positive. Please read the "About anti-virus detection" section in the README.md.
