### ISSUE TITLE
is this virus???

### ISSUE THREAD

**Issue by Aisultan14366** [FlyTechVideos/BluescreenSimulator#165]
My windows defender found TrojanDropper:Win64/Blusimul.ARA!MTB inside bluescreensimulator and then removed it

**Comment by demo308** [comment]
it is not virus it is false postive

**Comment by demo308** [comment]
Windows Defender: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26
Avast: https://support.avast.com/en-ww/article/Antivirus-scan-exclusions#pc
AVG: https://support.avg.com/SupportArticleView?l=en&urlName=avg-antivirus-scan-exclusion
Norton: https://support.norton.com/sp/en/us/home/current/solutions/v3672136
McAfee: https://www.mcafee.com/support/?page=shell&shell=article-view&articleId=TS102056
For other antiviruses, try searching for "<antivirus name> add exception"

**Comment by demo308** [comment]
```rust
Windows Defender: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26
Avast: https://support.avast.com/en-ww/article/Antivirus-scan-exclusions#pc
AVG: https://support.avg.com/SupportArticleView?l=en&urlName=avg-antivirus-scan-exclusion
Norton: https://support.norton.com/sp/en/us/home/current/solutions/v3672136
McAfee: https://www.mcafee.com/support/?page=shell&shell=article-view&articleId=TS102056
For other antiviruses, try searching for "<antivirus name> add exception"
```

**Comment by realthrottle** [comment]
it happened with me too

**Comment by SamyoFox** [comment]
Yes, it is a false-positive. Please read the "About anti-virus detection" section in the README.md.
