### ISSUE TITLE
Avast one stupid detection

### ISSUE THREAD

**Issue by LucaBuca17** [FlyTechVideos/BluescreenSimulator#166]
when BluescreenSimulator.exe was installed. it was blocked by avast one and marked as Trojan Horse

**Comment by SamyoFox** [comment]
Please read the "About anti-virus detection" section in the README.md

**Comment by LucaBuca17** [comment]
> Please read the "About anti-virus detection" section in the README.md

This was just for many users to mark it as a false negative.
