### ISSUE TITLE
EXE Generator broken

### ISSUE THREAD

**Issue by iiRoco** [FlyTechVideos/BluescreenSimulator#17]
Broken in [new-bluescreens](https://github.com/FlyTechVideos/BluescreenSimulator/tree/new-bluescreens)

[Screenshot](http://oi64.tinypic.com/34fjvxl.jpg)

it seems like it's not recognizing the strings?
due to that the generated .exe doesn't open/start

#Edit-1 
[Screenshort](https://cdn.discordapp.com/attachments/413430340388913171/550044925098721281/unknown.png)
Not recognizing anything at all
it makes a copy of the original BluescreenSimulator EXE

**Comment by jeuxjeux20** [comment]
The problem seems to come from the color parsing :/ weird that it works in cmd

**Comment by jeuxjeux20** [comment]
Should be fixed now.

**Comment by iiRoco** [comment]
Fixed in 0a17974936bfae2c99ae396ae1a531292249ed34

**Comment by iiRoco** [comment]
Still broken.. @jeuxjeux20

**Comment by iiRoco** [comment]
fixed in 367b09b
