### ISSUE TITLE
[Suggestion] Custom QR-Code Link

### ISSUE THREAD

**Issue by Ilyaviznitsa** [FlyTechVideos/BluescreenSimulator#174]
**Warning**
It's a suggestion not a issue!
**Suggestion**
Anyways, i was scanning a QR-Code from my custom BSOD, and it's a link to your channel
Can you make a option to change the link to the QR-Code please :(
(Note: Same suggestion was a Issue #158)

**Comment by Well236** [comment]
Bro I don't make videos also I'm subscribing to you

**Comment by Well236** [comment]
Oh okay

**Comment by Dimarar** [comment]
It's not a issue. It's what you wanted...

**Comment by Ilyaviznitsa** [comment]
I'm closing this issue
Reason: Can't be added
