### ISSUE TITLE
chrome isn't letting me download it

### ISSUE THREAD

**Issue by zurekzkieubasa** [FlyTechVideos/BluescreenSimulator#178]
![Zrzut ekranu 2024-04-01 213223](https://github.com/FlyTechVideos/BluescreenSimulator/assets/164732225/a7e80329-63bf-4ccd-8594-5ad35302d470)
It says it's ,,Dangerous virus'' and i know it is not cuz i downloaded it recently.
I don't know is it my PC issue or some codes.

**Comment by CinnamorollDing** [comment]
nah its a real virus mcafee said so
dont open

**Comment by Dimarar** [comment]
> nah its a real virus mcafee said so dont open

Bro is normal. Your antivirus is bad

**Comment by SamyoFox** [comment]
It's a false-postive. Please read the "About anti-virus detection" section in the README.md.
