### ISSUE TITLE
open or not?

### ISSUE THREAD

**Issue by Dimarar** [FlyTechVideos/BluescreenSimulator#181]
![image](https://github.com/FlyTechVideos/BluescreenSimulator/assets/112246243/64e32796-b30e-4831-8876-409cb6abf016)

my windows say this file is virus! what i gonna do?

**Comment by CinnamorollDing** [comment]
DON'T OPEN IT I'M GOING TO UNSUB THIS GUY HE MUST BE A HACKER IN DISGUISE
**DON'T OPEN**

**Comment by Dimarar** [comment]
> DON'T OPEN IT I'M GOING TO UNSUB THIS GUY HE MUST BE A HACKER IN DISGUISE **DON'T OPEN**

Bro you can open this. Kaspersky say it's normal file! Windows defender is piece of ####
