### ISSUE TITLE
Edge says no download: virus detected

### ISSUE THREAD

**Issue by CinnamorollDing** [FlyTechVideos/BluescreenSimulator#182]
ARE YOU A HACKER IN A DISGUISE? MY COMPUTER SAYS IT'S A VIRUS!!

**Comment by Ucda1212** [comment]
"IMPORTANT NOTE: It looks like by now, most antimalware vendors (falsely!) flag this as malware. The official (and only the official) download through the official Github (i.e. this page right here), is free of malware. Nonetheless, if you don't trust it, don't download it, or compile it yourself using the given source code. Thank you." - Download Page. You need to read everything before willingly downloading over the internet, or you will find yourself downloading a virus.

**Comment by kailando** [comment]
Same, @CinnamorollDing.

**Comment by SamyoFox** [comment]
It's a false-postive. Please read the "About anti-virus detection" section in the README.md.
