### ISSUE TITLE
Mcafee antivirus says it's a threat which name is "ti!3A0F137E7B29"

### ISSUE THREAD

**Issue by ayjemabo** [FlyTechVideos/BluescreenSimulator#184]
I can't open it

**Comment by CinnamorollDing** [comment]
NO check https://www.mcafee.com/support/?page=shell&shell=article-view&articleId=TS102056 I found it was SAFE totally SAFE
yeah. trust me

**Comment by ayjemabo** [comment]
> NO check https://www.mcafee.com/support/?page=shell&shell=article-view&articleId=TS102056 I found it was SAFE totally SAFE
> 
> yeah. trust me

Ok it works, I'm gonna close this issue

**Comment by CinnamorollDing** [comment]
It is prooved 10000000000% safe.

**Comment by ayjemabo** [comment]
Bro this was 5 months ago 💀💀

**Comment by poentavy** [comment]
It is safe bro
