### ISSUE TITLE
Custom colors don't work

### ISSUE THREAD

**Issue by ghost** [FlyTechVideos/BluescreenSimulator#187]
![image](https://github.com/FlyTechVideos/BluescreenSimulator/assets/58884890/23477737-374b-4ca2-932a-f344bae16748)

**Comment by FlyTechVideos** [comment]
#FA9093C is not a valid color code, as it consists of 7 characters instead of 6. You must fix your color code by dropping one character, e.g. #FA9093.

**Comment by FlyTechVideos** [comment]
Okay, looks like it's a bug -> #186
