### ISSUE TITLE
It isn't running

### ISSUE THREAD

**Issue by Ltlu1** [FlyTechVideos/BluescreenSimulator#189]
I used firefox to download and it pops up with an error that says something like: 'This file is malware and otherwise cannot be opened.' Even running it on administrator still does the **same thing**. And then after clicking ok on the error message, the file just self deletes.

**Comment by FlyTechVideos** [comment]
Firefox does not mind usually, Windows Defender however makes a fuss around that file. To whitelist it in Defender, please follow the guide: https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26#ID0EBF=Windows_11
