### ISSUE TITLE
Invalid markdown

### ISSUE THREAD

**Issue by mateohideg2** [FlyTechVideos/BluescreenSimulator#19]
Hello, I download the source code and I open "MainWindows.xaml", I find it in "Views", and it says "Invalid markdown, see the list of errors for more information" and there are 4 errors, what happened? I still can't edit the code

Errors:

2x XDG0008 XAML

2x XDG0012 XAML

**Comment by mateohideg2** [comment]
I click "Start", and it opens, now I can edit the code.

**Comment by jeuxjeux20** [comment]
ah yes, visual studio screws up again.

**Comment by mateohideg2** [comment]
Yes
