### ISSUE TITLE
Bluescreen opening in background

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [FlyTechVideos/BluescreenSimulator#2]
The bluescreen is sometimes opening in background of the currently used program. 
You can also shift+tab out of it.

**Comment by VukAnd** [comment]
I don't think that's possible to fix.

**Comment by dR1pT** [comment]
of course you can use shift+tab to exit
don't expect real bsod from this

**Comment by jeuxjeux20** [comment]
We can use `Topmost="True"` and `Focus`

**Comment by jeuxjeux20** [comment]
see #3

**Comment by Samyocord** [comment]
Disabling Shift+Tab can be done

**Comment by FlyTechVideos** [comment]
@Samyocord https://github.com/FlyTechVideos/BluescreenSimulator/issues/5

**Comment by FlyTechVideos** [comment]
Done
