### ISSUE TITLE
strange stuff with win9x (and win7) bsod

### ISSUE THREAD

**Issue by usernameisalreadyttaken** [FlyTechVideos/BluescreenSimulator#22]
ok so i just got the latest 3.0 version to test everything new and after trying to create a 9x bsod things just went wrong. I couldn't screenshot, alt+f4/f7/ctrl+alt+del did nothing, i got some error that kept showing up with the same time interval (https://cdn.discordapp.com/attachments/473555209961078785/550324677927501834/IMAG2751.jpg) until the whole app just crashed (and my screen resolution stayed in 800x600 or whatsoever)

also, if this is an important information, i first tried if the "press any key to continue" works, i pressed space and also tried to close it with a mouse click before doing anything else

**Comment by dR1pT** [comment]
interesting, which version of .NET you have?

**Comment by usernameisalreadyttaken** [comment]
the .net framework is 4.7.2

**Comment by usernameisalreadyttaken** [comment]
> interesting, which version of .NET you have?

the .net framework is 4.7.2

**Comment by dR1pT** [comment]
i will try to replicate this later

**Comment by dR1pT** [comment]
update: this happens on win 9x bsod and win 7 bsod

**Comment by jeuxjeux20** [comment]
Hm, weird, will add stacktrace and a closing option in the next commit.

**Comment by jeuxjeux20** [comment]
@usernameisalreadyttaken Please retry with the new branch `new-bsod-fixes` and tell us what is the stacktrace.

**Comment by dR1pT** [comment]
Interesting, BSODs work fine for me

**Comment by dR1pT** [comment]
@jeuxjeux20 This is up to you

**Comment by iiRoco** [comment]
Fixed in [new-bsod-fixes](https://github.com/FlyTechVideos/BluescreenSimulator/tree/new-bsod-fixes)
