### ISSUE TITLE
trying to create a bsod here's a screenshot of what went wrong

### ISSUE THREAD

**Issue by xAndrei166** [FlyTechVideos/BluescreenSimulator#25]
![eerwerwe](https://user-images.githubusercontent.com/31206758/53644752-fefb5080-3c3f-11e9-8fa5-ad4404f9a149.png)

i killed the task because it was overloading the thing

*is it a forkbomb and i don't know?!?!?!?!*

**Comment by jeuxjeux20** [comment]
That's probably caused due to some background progress task or key hooking. The 3.0 release a slightly bugged, the 3.1 release coming soon will be better.

**Comment by dR1pT** [comment]
Is this fixed? @jeuxjeux20

**Comment by jeuxjeux20** [comment]
@xAndrei166 any updates?

**Comment by dR1pT** [comment]
Let's assume it's fixed since OP is not responding
