### ISSUE TITLE
screen resolution on my pc got stuck on 800x600 and i cant change it

### ISSUE THREAD

**Issue by Techcraft7** [FlyTechVideos/BluescreenSimulator#30]
so i was messing around with the win 9x and win 7 bsod when my screen got stuck on 800x600.  I need the code that sets the screen resolution so i can revert this. (i cant change the resolution because it was a school pc)

**Comment by jeuxjeux20** [comment]
This issue has already been fixed since 3.1 as we removed the resolution things :/

Try to download 3.0 and close the app to see if the problem gets resolved.

**Comment by Techcraft7** [comment]
Thank you! (btw i fixed the school pc's screen using * another * tool)

**Comment by jeuxjeux20** [comment]
alright nice!
