### ISSUE TITLE
Rainbow just doesn't work.

### ISSUE THREAD

**Issue by ad2017gd** [FlyTechVideos/BluescreenSimulator#36]
So uh yeah I don't think this needs any explanation.

 
![image](https://user-images.githubusercontent.com/39013925/56475341-840c2480-648f-11e9-8b04-d9c2f1f2904a.png)

![image](https://user-images.githubusercontent.com/39013925/56475343-8d958c80-648f-11e9-98a7-300d83a0cb36.png)

Am I just really retarded or is it actually broken?

**Comment by iiRoco** [comment]
its broken in 3.1v so thanks for reporting this issue, wait for the new release.

**Comment by jeuxjeux20** [comment]
yup, #37 should fix this.
