### ISSUE TITLE
The Windows 7 BSOD style doesn't looks like the original one

### ISSUE THREAD

**Issue by Hanif1601** [FlyTechVideos/BluescreenSimulator#41]
Hello, can you fix the Windows 7 BSOD style on current version? It seems the text doesn't fill or little bit cropped while simulating Windows 7 BSOD style on my PC.

**Comment by boston2029** [comment]
Yeah, I saw that ummmm

**Comment by yum13241** [comment]
The font seems wrong.

**Comment by FlyTechVideos** [comment]
The W7 BSOD uses Lucida Console. I think it looks wrong simply because it is using full resolution, which the real W7 BSOD does not do. I do not think this can be fixed from our side except by crashing the graphics driver, which would truly turn this thing into malware :D
