### ISSUE TITLE
File is not signed

### ISSUE THREAD

**Issue by wooden-utensil** [FlyTechVideos/BluescreenSimulator#42]
Assembly isn't signed. Unknown publisher, sign the ClickOnce method.

**Comment by jeuxjeux20** [comment]
Well yes, but a cert costs thousands of dollars each year so it's a bit hard to sign apps.

**Comment by wooden-utensil** [comment]
@jeuxjeux20 Oh never knew that, thanks.

**Comment by mytja** [comment]
Hello!
I'm not the best at C#, but I want to contribute at least as a translator.
However, I signed version 3.1, which you can download here: https://github.com/mytja/BluescreenSimulator/releases/tag/3.1-signed
And also if you don't trust me ;-) here is a scan from virustotal: https://www.virustotal.com/gui/file/203d68da8d71574f73b10dbd981a9b06d1268fef4e7eb2900ac07c1909827850/detec
If you need me to sign more versions, I'm here for you.
Here is a tutorial on how to sign apps:
1. Download latest version of EXE and signer.exe (https://github.com/mytja/Signer.exe)
2. Open CMD
3. If it is already located in your user folder (C:\Users\<username>), then execute "cd Downloads", but if it's not, then execute: "cd C:\Users\<username>\Downloads"
4. Execute "signer /sign FlyTechVideos BluescreenSimulator.exe
5. If warning pops up, just choose Yes

And your file is signed! Super easy!

Hope that helps! :)

**Comment by jeuxjeux20** [comment]
Thanks for your contribution! However, self-signed certificates are considered as unsafe by Windows, unfortunately.

**Comment by mytja** [comment]
I understand.
Thank you
Mytja
