### ISSUE TITLE
Hebrew gets glitched out

### ISSUE THREAD

**Issue by TheShwarma** [FlyTechVideos/BluescreenSimulator#46]
Obviously I can't supply a screenshot... See it yourself. Just copy paste Hebrew words like "דוגמא" (example) and run the program. You'll see it glitching out, probably related to ASCII or something.

**Comment by iiRoco** [comment]
Can you explain more?
http://0x0.st/z6Hq.png
seems working for me

**Comment by xAyman** [comment]
uuuuuuhhh

**Comment by TheShwarma** [comment]
Ok perhaps it was fixed
