### ISSUE TITLE
File deleting itself

### ISSUE THREAD

**Issue by nathrider** [FlyTechVideos/BluescreenSimulator#48]
When I create a file, the file gets deleted after less than 10 seconds and if i leave bluescreenSimulator it's also delete.
There's a video here. PS: Sorry for the bad english.
[Video.zip](https://github.com/FlyTechVideos/BluescreenSimulator/files/3828695/Video.zip)

**Comment by nathrider** [comment]
Add me on discord if you want to talk: [JLP] Draymen 00#3730

**Comment by nathrider** [comment]
PPS: Using IExpress do the same thing

**Comment by iiRoco** [comment]
Hi this could be an anti-virus issue, definitely not the program itself.
