### ISSUE TITLE
Prevent common key combinations

### ISSUE THREAD

**Issue by FlyTechVideos** [FlyTechVideos/BluescreenSimulator#5]
Prevent combinations from closing the BSOD.

- Alt+Tab
- Windows-Key
- Alt+F4

Do NOT disable Ctrl+Alt+Del and the intended F7.

**Comment by Samyocord** [comment]
I'm doing this rn

**Comment by jeuxjeux20** [comment]
Fix ready in #14

**Comment by FlyTechVideos** [comment]
Fixed in #14
