### ISSUE TITLE
Microsoft Says that the application cannot open

### ISSUE THREAD

**Issue by MartinZolo** [FlyTechVideos/BluescreenSimulator#53]
So Windows Defender Says No

**Comment by Biggamesjames50** [comment]
Same it prevented it from running and I would like to know why

**Comment by Biggamesjames50** [comment]
It is because it is from an unknown publisher

**Comment by iiRoco** [comment]
False positive.
[AV Scan](https://www.virustotal.com/gui/file/a872ab63fd3e70627d7bf28a74045a5fca407d79a950ac1fdbcecd6b7672469f/) you can see here its not even flagged by any other antiviruses
