### ISSUE TITLE
Feature Request: Windows 7/10 BSOD closing after 100%

### ISSUE THREAD

**Issue by MrNessuno** [FlyTechVideos/BluescreenSimulator#56]
Windows 10 and 7 BSOD will not close after 100%. Can be an option to choose to close them after 100% (maybe with a little delay) so is possible to open some other commands with the "Command after complete" feature like some bat files or other things. Or a loop of different BSODs.

Version: 3.1
O.S.: Windows 10

**Comment by Mar10Josh** [comment]
Wow! That really might help out.

**Comment by SamyoFox** [comment]
Implemented with #99.
