### ISSUE TITLE
Windows defender detects .exe of Bsod simulator as a virus

### ISSUE THREAD

**Issue by sergiorgb** [FlyTechVideos/BluescreenSimulator#58]
![image](https://user-images.githubusercontent.com/59933966/89217325-99786580-d591-11ea-9eda-acc4d7791871.png)

**Comment by iiRoco** [comment]
this is a false positive.
[VirusTota scanl](https://www.virustotal.com/gui/file/a872ab63fd3e70627d7bf28a74045a5fca407d79a950ac1fdbcecd6b7672469f/)
