### ISSUE TITLE
Permanent cursor suppression for user if you start a BSOD with a delay

### ISSUE THREAD

**Issue by distay0xGit** [FlyTechVideos/BluescreenSimulator#59]
I actually caused this by accident, and for my super-admin user, it's left my cursor permanently suppressed when I try to log in. I had to switch to a completely different user in order to use my mouse.

Using BSOD Simulator v3.1.

EDIT: When I was meaning suppression, I meant that the cursor is invisible, and can't be moved by user input.

EDIT 2: If you're also able to make a program that reverses the cursor suppression, that would be great.

Windows 10 Home Version 2004 (Build 19041.329)
Alienware 17 R2
Specs: Intel i7 4710-HQ CPU, Intel HD Graphics 4600 Primary GPU, NVIDIA GeForce GTX 970M Secondary GPU, 500GB Samsung 860EVO SSD

**Comment by boston2029** [comment]
What do you mean by suppressed?

**Comment by boston2029** [comment]
Unplug your PC. If you have laptop, unplug and let the battery die. Well first try Ctrl + Alt + Del; that stopped auto clicking my auto clicker when I couldn't get it to turn off! Good luck

**Comment by boston2029** [comment]
> What do you mean by suppressed?

ignore this comment that i am quoting, i just read the rest of your issue and saw what you meant.

**Comment by boston2029** [comment]
Press F7. That's how you stop the BSOD and the cursor suppression is to make the BSOD look more realistic, not like you're just on some dumb old prank website.

**Comment by SamyoFox** [comment]
Couldn't reproduce.
