### ISSUE TITLE
Can't launch

### ISSUE THREAD

**Issue by boston2029** [FlyTechVideos/BluescreenSimulator#60]
Hi. So I extracted the ZIP file, and I don't know what to launch. Someone please help. (bc i wanna prank my dad and make him freak out)

**Comment by jeuxjeux20** [comment]
You probably extracted the zip file which contains the source code of the project, which cannot be directly executed, however, you can download the release right there: https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.1 ; you just have to download the BluescreenSimulator.exe file and experience the maximum pranking experience!

**Comment by boston2029** [comment]
Great, thanks. Now I need to know one more thing:
Is this safe? Does it actually crash my PC?

**Comment by jeuxjeux20** [comment]
It won't crash it, once you run the executable you will see a menu where you can customize your bluescreen and display it, once displayed it will just display a fake bluescreen (surprisingly) that you can close manually by pressing F7.
