### ISSUE TITLE
Can't exit BSOD. Help #bug

### ISSUE THREAD

**Issue by josiauh** [FlyTechVideos/BluescreenSimulator#65]
While I was messing with BSOD sim, I can't get it off. Help!

**Comment by danieleremin** [comment]
Try pressing F7 or Alt+F4

**Comment by jellytoaster** [comment]
> Did you try pressing F7 or Alt+F4 ?

I have the same problem. The only way i can close it is using task manager.

**Comment by Mar10Josh** [comment]
> Did you try pressing F7 or Alt+F4 ?

I have but it can't work!

**Comment by jellytoaster** [comment]
I just found the problem... I had function lock off

**Comment by Alexander-Maples** [comment]
> I have but it can't work!
Did you try left clicking and then hitting F7?

**Comment by yum13241** [comment]
PSA: download SuperF4, set it up, then you will be able to force kill any app. Alt+F4 only asks the app if it will quit.

**Comment by FlyTechVideos** [comment]
Should be fixed in 3.4.0: https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0
