### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by LCS2020AtGitHub** [FlyTechVideos/BluescreenSimulator#70]
So what do we do

(Closing in 3 mins)

**Comment by iiRoco** [comment]
https://github.com/FlyTechVideos/BluescreenSimulator/releases

**Comment by LCS2020AtGitHub** [comment]
+iiRoco I'll see if that works.

**Comment by FlyTechVideos** [comment]
https://github.com/FlyTechVideos/BluescreenSimulator/releases
