### ISSUE TITLE
Commands do not execute

### ISSUE THREAD

**Issue by TangledWiresYT** [FlyTechVideos/BluescreenSimulator#72]
If I put in a command to execute after the blue screen (in this case 'shutdown /r') and generate the executable, then run it, the blue screen appears but the machine does not reboot. Am I doing something wrong?

**Comment by iiRoco** [comment]
Did you enable unsafe mode?

**Comment by KodedKid** [comment]
Yes i have.

**Comment by Pranay-Chopra** [comment]
Ya I have this issue too. My command is BluescreenSimulator.exe -c "shutdown /r /f /t 0" --win10 --enable-unsafe

**Comment by SamyoFox** [comment]
Fixed with #99.
