### ISSUE TITLE
BSOD command isnt declared stopped untill manually quit

### ISSUE THREAD

**Issue by PO144** [FlyTechVideos/BluescreenSimulator#73]
If the command is in a batch file, cmd won't continue executing the past commands until the user exits(it also won't progress automatically when the progress reaches a 100%).

**Comment by PO144** [comment]
I am guessing this is also the reason why commands at "command after complete" won't execute.

**Comment by FlyTechVideos** [comment]
The reason for that was that unsafe mode was broken and the command was never actually executed. Please try out the latest version where this is fixed: https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0
