### ISSUE TITLE
does not find tutorial video

### ISSUE THREAD

**Issue by joislahdo22** [FlyTechVideos/BluescreenSimulator#76]
hello, I have installed this simulator, and idk to download the .exe window need help

**Comment by Alexander-Maples** [comment]
when you say you can't download, you mean the "generate cmd/exe" feature right?

**Comment by SamyoFox** [comment]
You can find the current release at [here](https://github.com/FlyTechVideos/BluescreenSimulator/releases), the generated .exe file should be in the same directory where you ran the program in.
