### ISSUE TITLE
Why can't i change the icon for the .exe file?

### ISSUE THREAD

**Issue by Babeluka7** [FlyTechVideos/BluescreenSimulator#79]
I tried to change the icon to prank my friends, but i cannot se the option "change icon" on the "properties" window. (this is for version 3.2)

**Comment by Alexander-Maples** [comment]
I do not believe changing the icon is possible with the app itself, however [HackBGRT ](https://github.com/Metabolix/HackBGRT) is a great way to do this.

**Comment by Babeluka7** [comment]
> I do not believe changing the icon is possible with the app itself, however if you copy the command it shows before you click the "Ok" button and save that in a .bat file, you can use the [BAT to EXE Converter](http://www.f2ko.de/programs.php?pid=b2e) (shown in this fly tech video: [Tutorial (Virus): Make Windows reboot after startup](https://www.youtube.com/watch?v=zrGjTlqOY74)) to change the icon. Note: the link in that video does not have a download button that i could find so [here](https://www.majorgeeks.com/files/details/bat_to_exe_converter.html) is an alternate download.

Hi, i tried to do that, but i still do not see the "change icon" button. Did you mean to i change the icon in the app?

**Comment by Babeluka7** [comment]
> > Hi, i tried to do that, but i still do not see the "change icon" button. Did you mean to i change the icon in the app?
> 
> Yes use the app to generate a new exe but before you do select the Icon option to the left and give it a path to your icon

Thanks for helping!

**Comment by Alloyd854** [comment]
Try Resource Hacker

**Comment by Alexander-Maples** [comment]
> Try Resource Hacker

Do you have a download link?

**Comment by Alloyd854** [comment]
http://www.angusj.com/resourcehacker/

**Comment by Alexander-Maples** [comment]
@Alloyd854 Works like a charm, EXCEPT in the folder it was in when the icon was changed. but that's not your fault

**Comment by FlyTechVideos** [comment]
The simulator never supported changing the icon. Please use Resource Hacker for that.
