### ISSUE TITLE
Custom colors fail in a generated exe file (3.2)

### ISSUE THREAD

**Issue by Alexander-Maples** [FlyTechVideos/BluescreenSimulator#80]
If you use custom colors and then generate an exe/cmd it says:
```
Something bad occurred when parsing the color: #FA90909,
System.FormatException: Token is not valid.
at MS.Internal.Parsers.ParseColor(String color, IFormatProvider formatprovider, ITypeDescriptorContext context)
at System.Windows.Media.ColorConverter.ConvertFromString(String value)
at BluescreenSimulator.CmdParameterAttribute.TryGetColor(String c, Color& result)
```
any idea why/how to fix? Sorry for mouse in pic.
![2021-04-29 14_11_14-](https://user-images.githubusercontent.com/74429872/116605314-ddb44e80-a8f4-11eb-838d-f75b9aec2d21.png)

**Comment by GavinGoGaming** [comment]
getting this same error. any fix?

**Comment by impossiblepro** [comment]
Try 3.1. ... maybe that works.

**Comment by RaspberryKitty1** [comment]
same error

**Comment by Firepup6500** [comment]
This error occurred in ver 3.1

**Comment by Herobrine8761** [comment]
I am also having the same issue. When I created one .EXE file, it showed up some random error about custom color and then runs the bluescreen with blue color.
