### ISSUE TITLE
Missing text in .exe generated file

### ISSUE THREAD

**Issue by Babeluka7** [FlyTechVideos/BluescreenSimulator#81]
I generated a .exe file and the bottom text (a.k.a. more info, support person, stop code) i think has a word limit, because, for example, i typed in "Kat will liv yu aloune if yu subscraibe tu da chenel: *link*" and it just says: "Kat will liv yu aloune if yu subscraibe tu da chen" So please fix this! (It only happens on the .exe, when i click the "give me an error" button, everything works)

P.S. Also, when i try to put an emoji like this: "ʕ•ᴥ•ʔ", it just says a bunch of gibberish, like "#/"&(/$&"&" (That happens in the .exe generated file only)

This problems happened on v3.2

**Comment by MrNobody326** [comment]
I had the same problem

**Comment by falseCloud** [comment]
This is common issue with compiling portable applications.

**Comment by FlyTechVideos** [comment]
Should be fixed in 3.4.0: https://github.com/FlyTechVideos/BluescreenSimulator/releases/tag/3.4.0
