### ISSUE TITLE
Malwarebytes false positive

### ISSUE THREAD

**Issue by MrNobody326** [FlyTechVideos/BluescreenSimulator#83]
Malwarebytes detects this a riskware.badjoke and i cant use the program.

**Comment by iiRoco** [comment]
It's a false positive, Add the executable to the exclusion list or turn off the protection.

**Comment by MrNobody326** [comment]
> It's a false positive, Add the executable to the exclusion list or turn off the protection.

Thanks! Its very cool. I'll use it to prank my tech savvy friends :)
