### ISSUE TITLE
.exe

### ISSUE THREAD

**Issue by franck403** [FlyTechVideos/BluescreenSimulator#84]
where is the .exe

**Comment by AnonimFan** [comment]
compile it in visual studio

**Comment by franck403** [comment]
But its not working the visual studio

**Comment by iiRoco** [comment]
What executable are you exactly trying to find?

**Comment by franck403** [comment]
Him to make the image blue

**Comment by AnonimFan** [comment]
@franck403 
https://github.com/FlyTechVideos/BluescreenSimulator/releases/download/3.2/BluescreenSimulator.exe there is the exe file

**Comment by SamyoFox** [comment]
You can find the current release at [here](https://github.com/FlyTechVideos/BluescreenSimulator/releases), the generated .exe file should be in the same directory where you ran the program in.
