### ISSUE TITLE
How do you use the "Command after Complete Box?"

### ISSUE THREAD

**Issue by impossiblepro** [FlyTechVideos/BluescreenSimulator#86]
I cant use the "Command after complete" Box, i've tried many Command line commands, like regedit, but they don't run after it's complete. Please Help Me

**Comment by iiRoco** [comment]
IIRC you need to launch the BSOD executable with --enable-unsafe for commands to work

![image](https://user-images.githubusercontent.com/43659330/128490957-5cc479da-7957-4d6b-8a75-f44ed263401f.png)

**Comment by moglol** [comment]
> IIRC you need to launch the BSOD executable with --enable-unsafe for commands to work
> 
> ![image](https://user-images.githubusercontent.com/43659330/128490957-5cc479da-7957-4d6b-8a75-f44ed263401f.png)

i tried it and still dosent work, i do have to type  BluescreenSimulator --enable-unsafe --win10 
im on windows 11 insider if that matters

**Comment by SamyoFox** [comment]
Fixed with #99
