### ISSUE TITLE
Cant find the exe or cmd file

### ISSUE THREAD

**Issue by AliALasfoor13YT** [FlyTechVideos/BluescreenSimulator#87]
**Where is the file i am searching for it please msg me whats the problem at alialasfoorplays@gmail.com 
I  will say if the problem is fixed thank you**

**Comment by SamyoFox** [comment]
What file are you searching?

(Also: Why should we contact you via e-mail if we can contact you here?)

**Comment by SamyoFox** [comment]
The generated .exe file should be in the same directory where you ran the program in.
