### ISSUE TITLE
Crashed App

### ISSUE THREAD

**Issue by Windows27215** [FlyTechVideos/BluescreenSimulator#88]
hey, my app is crashed I open this blue screen simulator.exe,
![Untitled13](https://user-images.githubusercontent.com/83114019/130720673-dd5f4b4d-5a04-4ac8-a3fe-bf1d8e8f5b8e.png)
 and then the app keeps crashing

**Comment by staticRoco** [comment]
Not enough info was provided, re-open if it occurs again.
