### ISSUE TITLE
EXE Generator gives an error.

### ISSUE THREAD

**Issue by Charlore** [FlyTechVideos/BluescreenSimulator#89]
When trying to generate an EXE file, it throws an error stating: 
![Thrown error](https://user-images.githubusercontent.com/67887540/130894784-90cbf006-6332-4661-b821-b04af2fbb24e.PNG)

It then states that it created the EXE file even though it hasn't:
![I wish you had](https://user-images.githubusercontent.com/67887540/130895426-456ac772-0e5e-46ce-bff9-71e5cd324e71.PNG)

I tried creating it manually via IExpress but it throws this error two times:
![2 errors thrown](https://user-images.githubusercontent.com/67887540/130896312-5c6b37c6-e597-413b-bddb-fe1703cc30ae.PNG)

But then it shows a bluescreen with half the text missing i.e. More info, Support Person, Stop code, colour and the QR code shows even though I set it to hide it.
Any help to fix this would be much appreciated!

**Comment by SamyoFox** [comment]
Color parsing problem fixed with #98, couldnt recreate the SED file opening error.
