### ISSUE TITLE
Add XP/Vista/7 Mode

### ISSUE THREAD

**Issue by FlyTechVideos** [FlyTechVideos/BluescreenSimulator#9]
Add mode to generate XP/Vista/7-like BSODs. Any way to modify screen resolution without admin rights? Maybe a borderless fullscreened CMD prompt?

- [x]  XP/Vista/7 Bsod
- [x]  modify screen resolution

**Comment by jeuxjeux20** [comment]
every video game can modify the resolution so i think we can do that

**Comment by iiRoco** [comment]
All done in 9eff280bd257666044e38b7399c8b226b3ad0b33
