### ISSUE TITLE
When I run it, MikuMikuEffect gives me an initialize error.

### ISSUE THREAD

**Issue by Icametoforkprojects23** [FlyTechVideos/BluescreenSimulator#92]
I have MikuMikuEffect downloaded on my PC, but it gives me an error every time I run BluescreenSimulator.
Does this open in MME?
![Help](https://user-images.githubusercontent.com/88011039/132922603-8014fdcc-e4a5-4483-b774-4081390e211b.png)

**Comment by SamyoFox** [comment]
BluescreenSimulator is a application, not a MMD plugin.
