### ISSUE TITLE
Generated exe reports as "malicous" in Windows Defender

### ISSUE THREAD

**Issue by matu6968** [FlyTechVideos/BluescreenSimulator#93]
I was creating the exe in the BSOD simulator and when the exe was generated, Windows Defender reported the exe as "malicious" and the name was called for the so called "malicious" program was Trojan:Win32/Sabisik.FL.A!ml But the exe contained nothing but the script to run the BSOD.  Must be fixed soon.
![Screenshot_5](https://user-images.githubusercontent.com/89382946/134729659-40827805-2a2e-40a7-b8ef-79e82196f77b.png)

**Comment by SurvExE-Pc** [comment]
Antiy-AVL

Trojan/Generic.ASMalwS.34893AD
ClamAV

Win.Packed.Badjoke-9881802-0
Cylance

Unsafe
Cynet

Malicious (score: 100)
ESET-NOD32

MSIL/BadJoke.WU
Malwarebytes

RiskWare.BadJoke
Microsoft

Trojan:Win32/Sabsik.FL.B!ml
Yandex

Trojan.Encoder!931oizK4Ixw

**Comment by SurvExE-Pc** [comment]
https://www.virustotal.com/gui/file/e9cfdc8f6ef115ffff54991c69832a8e0421db738badaa92420fde0417f3f753?nocache=1

**Comment by SurvExE-Pc** [comment]
Scared my pants off

**Comment by iiRoco** [comment]
It's a false positive.
